CREATE TABLE asignaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id INT NOT NULL,
    funcionario_id INT NOT NULL,
    asignado_por INT,
    fecha_asignacion TIMESTAMP DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE,
    observaciones TEXT,
    CONSTRAINT pk_asignaciones PRIMARY KEY (id),
    CONSTRAINT fk_asignaciones_denuncia FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_asignaciones_funcionario  FOREIGN KEY (funcionario_id) REFERENCES funcionarios (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_asignaciones_asignado_por FOREIGN KEY (asignado_por) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE
);