CREATE TABLE audiencias (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    denuncia_id INT NOT NULL,
    fiscal_id INT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    lugar VARCHAR(300) NULL,
    tipo VARCHAR(100) NULL,
    estado VARCHAR(50) NULL,
    acta TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT now(),

    CONSTRAINT audiencias_pkey
        PRIMARY KEY (id),

    CONSTRAINT audiencias_denuncia_id_fkey
        FOREIGN KEY (denuncia_id)
        REFERENCES denuncias (id)
        DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT audiencias_fiscal_id_fkey
        FOREIGN KEY (fiscal_id)
        REFERENCES fiscales (id)
        DEFERRABLE INITIALLY IMMEDIATE
);
