CREATE TABLE denunciados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id              INT NOT NULL,
    persona_id               INT NOT NULL,
    relacion_con_denunciante VARCHAR(100),
    descripcion_fisica       TEXT,

    CONSTRAINT pk_denunciados PRIMARY KEY (id),
    CONSTRAINT uq_denunciados_den_per UNIQUE (denuncia_id, persona_id),
    CONSTRAINT fk_denunciados_denuncia FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_denunciados_persona FOREIGN KEY (persona_id)  REFERENCES personas  (id) DEFERRABLE INITIALLY IMMEDIATE
);
