CREATE TABLE derivaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id INT NOT NULL,
    fiscal_id INT NOT NULL,
    derivado_por INT NOT NULL,
    fecha_derivacion TIMESTAMP DEFAULT NOW(),
    motivo TEXT,
    estado VARCHAR(50),
    observaciones TEXT,
    CONSTRAINT pk_derivaciones PRIMARY KEY (id),
    CONSTRAINT fk_derivaciones_denuncia FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_derivaciones_fiscal FOREIGN KEY (fiscal_id) REFERENCES fiscales (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_derivaciones_derivado_por FOREIGN KEY (derivado_por) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE
);