CREATE TABLE "distritos_fiscales" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "sede" varchar(200),
  "ubigeo_id" int,
  "activo" boolean DEFAULT true
);