CREATE TABLE estados_denuncia (
    id          INT GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(80)  NOT NULL,
    descripcion VARCHAR(300),
    es_final    BOOLEAN      DEFAULT FALSE,
    orden       INT,
    CONSTRAINT pk_estados_denuncia PRIMARY KEY (id),
    CONSTRAINT uq_estados_denuncia_nom UNIQUE (nombre),
);