CREATE TABLE evidencias (
    id                  INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id         INT             NOT NULL,
    tipo_id             INT             NOT NULL,
    nombre_archivo      VARCHAR(255)    NOT NULL,
    url_almacenamiento  VARCHAR(500)    NOT NULL,
    tamanio_bytes       BIGINT,
    mime_type           VARCHAR(100),
    descripcion         VARCHAR(300),
    subido_por          INT,
    created_at          TIMESTAMP       DEFAULT NOW(),

    CONSTRAINT pk_evidencias             PRIMARY KEY (id),
    CONSTRAINT chk_evidencias_tamanio    CHECK (tamanio_bytes IS NULL OR tamanio_bytes > 0),
    CONSTRAINT fk_evidencias_denuncia    FOREIGN KEY (denuncia_id)  REFERENCES denuncias      (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_evidencias_tipo        FOREIGN KEY (tipo_id)      REFERENCES tipos_evidencia (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_evidencias_subido_por  FOREIGN KEY (subido_por)   REFERENCES usuarios        (id) DEFERRABLE INITIALLY IMMEDIATE
);
