CREATE TABLE "fiscales" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int UNIQUE NOT NULL,
  "persona_id" int NOT NULL,
  "distrito_fiscal_id" int NOT NULL,
  "especialidad" varchar(150),
  "codigo_fiscal" varchar(50) UNIQUE,
  "activo" boolean DEFAULT true

    FOREIGN KEY (distrito_fiscal_id)
    REFERENCES distritos_fiscales(id)
);