CREATE TABLE historial_estados (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id INT NOT NULL,
    estado_anterior_id INT,
    estado_nuevo_id INT NOT NULL,
    usuario_id INT NOT NULL,
    motivo TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT pk_historial_estados PRIMARY KEY (id),
    CONSTRAINT fk_historial_estado_anterior FOREIGN KEY (estado_anterior_id) REFERENCES estados_denuncia (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_historial_denuncia FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_historial_estado_anterior FOREIGN KEY (estado_anterior_id) REFERENCES estados_denuncia (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_historial_estado_nuevo FOREIGN KEY (estado_nuevo_id) REFERENCES estados_denuncia (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) DEFERRABLE INITIALLY IMMEDIATE
);