CREATE TABLE notificaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT NOT NULL,
    denuncia_id INT,
    canal VARCHAR(20) NOT NULL,
    asunto VARCHAR(300),
    mensaje TEXT NOT NULL,
    estado VARCHAR(20) DEFAULT 'PENDIENTE',
    intentos INT DEFAULT 0,
    enviado_at  TIMESTAMP,
    created_at  TIMESTAMP DEFAULT NOW(),

    CONSTRAINT pk_notificaciones PRIMARY KEY (id),
    CONSTRAINT fk_notif_usuario FOREIGN KEY (usuario_id)  REFERENCES usuarios  (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_notif_denuncia FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE
);
