CREATE TABLE personas(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    dni VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    genero VARCHAR(20),
    telefono VARCHAR(20),
    email_contacto VARCHAR(150),
    ubigeo_id INT,
    direccion VARCHAR(300),
    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT pk_personas PRIMARY KEY (id),
    CONSTRAINT uq_personas_dni UNIQUE (dni),
    CONSTRAINT fk_personas_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT fk_personas_ubigeo
        FOREIGN KEY (ubigeo_id)
        REFERENCES ubigeo(id)
        DEFERRABLE INITIALLY IMMEDIATE
);