CREATE TABLE resoluciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id INT NOT NULL,
    fiscal_id INT NOT NULL,
    tipo_resolucion VARCHAR(100),
    descripcion TEXT NOT NULL,
    fecha_resolucion TIMESTAMP DEFAULT NOW(),
    documento_url VARCHAR(500),
    CONSTRAINT pk_resoluciones PRIMARY KEY (id),
    CONSTRAINT uq_resoluciones_denuncia UNIQUE (denuncia_id),
    CONSTRAINT fk_resoluciones_denuncia FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_resoluciones_fiscal FOREIGN KEY (fiscal_id) REFERENCES fiscales (id) DEFERRABLE INITIALLY IMMEDIATE
);