CREATE TABLE testigos (
    id             INT GENERATED BY DEFAULT AS IDENTITY,
    denuncia_id    INT         NOT NULL,
    persona_id     INT,
    nombre_anonimo VARCHAR(100),
    declaracion    TEXT,
    created_at     TIMESTAMP   DEFAULT NOW(),

    CONSTRAINT pk_testigos            PRIMARY KEY (id),
    CONSTRAINT chk_testigos_identidad CHECK (persona_id IS NOT NULL OR nombre_anonimo IS NOT NULL),
    CONSTRAINT fk_testigos_denuncia   FOREIGN KEY (denuncia_id) REFERENCES denuncias (id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_testigos_persona    FOREIGN KEY (persona_id)  REFERENCES personas  (id) DEFERRABLE INITIALLY IMMEDIATE
);
