CREATE TABLE "tipos_delito" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoria_id" int NOT NULL,
  "nombre" varchar(200) NOT NULL,
  "articulo_cp" varchar(50),
  "descripcion" text,
  "gravedad" varchar(20),
  "activo" boolean DEFAULT true

    FOREIGN KEY (categoria_id)
    REFERENCES categorias_delito(id)
);