CREATE TABLE tipos_evidencia (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(80) NOT NULL,

    CONSTRAINT pk_tipos_evidencia PRIMARY KEY (id),
    CONSTRAINT uq_tipos_evidencia_nombre UNIQUE (nombre),
);
