CREATE TABLE ubigeo (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(6) NOT NULL,
    departamento VARCHAR(100) NOT NULL,
    provincia VARCHAR(100) NOT NULL,
    distrito VARCHAR(100) NOT NULL,

    CONSTRAINT pk_ubigeo PRIMARY KEY (id),
    CONSTRAINT uq_ubigeo_codigo UNIQUE (codigo)
);