CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT  AS IDENTITY,
    email   VARCHAR(200) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    activo  BOOLEAN DEFAULT TRUE,
    ultimo_acceso TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_At TIMESTAMP,

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_email UNIQUE (email),  
);