CREATE TABLE usuario_roles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id INT NOT NULL,
    rol_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT pk_usario_roles PRIMARY KEY (id),

    CONSTRAINT fk_usuario_roles_usuario 
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        DEFERRABLE INITIALLY IMMEDIATE,

    CONSTRAINT fk_usuario_roles_rol
        FOREIGN KEY (rol_id)
        REFERENCES roles(id) 
        DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT uq_usuario_roles UNIQUE (usuario_id, rol_id) 
);